## Function to get user selection of the glass of the drink and provide list of options

In [1]:
import pandas as pd
import requests
import json
import matplotlib
#pd.options.display.max_rows = 999
#pd.options.display.max_columns = 999

%matplotlib inline

In [2]:
# Search for drink category
def drink_glass(glass):
    url = f"https://www.thecocktaildb.com/api/json/v1/1/filter.php?g={str(glass)}"
    r = requests.get(url)
    df = pd.DataFrame(r.json()["drinks"])
    return df.dropna(axis='columns', how='all')

In [3]:
# for a given name, requires to replace " " by "_"
drink_glass("Punch_bowl")

,strDrink,strDrinkThumb,idDrink
0,Apple Grande,https://www.thecocktaildb.com/images/media/dri...,16289
1,Apricot punch,https://www.thecocktaildb.com/images/media/dri...,15849
2,Artillery Punch,https://www.thecocktaildb.com/images/media/dri...,12870
3,Aztec Punch,https://www.thecocktaildb.com/images/media/dri...,14364
4,Bloody Punch,https://www.thecocktaildb.com/images/media/dri...,178312
5,Brain Fart,https://www.thecocktaildb.com/images/media/dri...,17120
6,Cranberry Punch,https://www.thecocktaildb.com/images/media/dri...,12890
7,Egg Nog #4,https://www.thecocktaildb.com/images/media/dri...,12910
8,Halloween Punch,https://www.thecocktaildb.com/images/media/dri...,178313
9,Holloween Punch,https://www.thecocktaildb.com/images/media/dri...,12954
10,Mudslinger,https://www.thecocktaildb.com/images/media/dri...,16041
11,Pink Penocha,https://www.thecocktaildb.com/images/media/dri...,16992
12,Rum Punch,https://www.thecocktaildb.com/images/media/dri...,14978
13,Sunny Holiday Punch,https://www.thecocktaildb.com/images/media/dri...,13042

In [4]:
# needs to be exact
# list of different categories for this db
url_list_origin = "https://www.thecocktaildb.com/api/json/v1/1/list.php?g=list"
ra = requests.get(url_list_origin)
df = pd.DataFrame(ra.json()["drinks"])
df

                    strGlass
0             Highball glass
1             Cocktail glass
2        Old-fashioned glass
3              Collins glass
4          Pousse cafe glass
5            Champagne flute
6         Whiskey sour glass
7             Brandy snifter
8           White wine glass
9        Nick and Nora Glass
10           Hurricane glass
11                Coffee mug
12                Shot glass
13                       Jar
14          Irish coffee cup
15                Punch bowl
16                   Pitcher
17                Pint glass
18                Copper Mug
19                Wine Glass
20             Cordial glass
21                  Beer mug
22  Margarita/Coupette glass
23              Beer pilsner
24                Beer Glass
25             Parfait glass
26                 Mason jar
27           Margarita glass
28             Martini Glass
29             Balloon Glass
30               Coupe Glass
31