## Function to get user selection of the category of the food and provide list of options

In [1]:
import pandas as pd
import requests
import json
import matplotlib
#pd.options.display.max_rows = 999
#pd.options.display.max_columns = 999

%matplotlib inline

In [4]:
# this function returns the list of the meals given origin
def meal_category(category):
    url = f"https://www.themealdb.com/api/json/v1/1/filter.php?c={str(category)}"
    r = requests.get(url)
    df = pd.DataFrame(r.json()["meals"])
    return df.dropna(axis='columns', how='all')

In [5]:
# testing the function works
meal_category("Seafood")

,strMeal,strMealThumb,idMeal
0,Baked salmon with fennel & tomatoes,https://www.themealdb.com/images/media/meals/1...,52959
1,Cajun spiced fish tacos,https://www.themealdb.com/images/media/meals/u...,52819
2,Escovitch Fish,https://www.themealdb.com/images/media/meals/1...,52944
3,Fish pie,https://www.themealdb.com/images/media/meals/y...,52802
4,Fish Stew with Rouille,https://www.themealdb.com/images/media/meals/v...,52918
5,Garides Saganaki,https://www.themealdb.com/images/media/meals/w...,52764
6,Honey Teriyaki Salmon,https://www.themealdb.com/images/media/meals/x...,52773
7,Kedgeree,https://www.themealdb.com/images/media/meals/u...,52887
8,Kung Po Prawns,https://www.themealdb.com/images/media/meals/1...,52946
9,Laksa King Prawn Noodles,https://www.themealdb.com/images/media/meals/r...,52821
10,Mediterranean Pasta Salad,https://www.themealdb.com/images/media/meals/w...,52777
11,Recheado Masala Fish,https://www.themealdb.com/images/media/meals/u...,52809
12,Salmon Avocado Salad,https://www.themealdb.com/images/media/meals/1...,52960
13,Salmon Prawn Risotto,https://www.themealdb.com/images/media/meals/x...,52823
14,Saltfish and Ackee,https://www.themealdb.com/images/media/meals/v...,52936
15,Seafood fideuà,https://www.themealdb.com/images/media/meals/w...,52836
16,Shrimp Chow Fun,https://www.themealdb.com/images/media/meals/1...,52953
17,Three Fish Pie,https://www.themealdb.com/images/media/meals/s...,52882
18,Tuna and Egg Briks,https://www.themealdb.com/images/media/meals/2...,52975
19,Tuna Nicoise,https://www.themealdb.com/images/media/meals/y...,52852

In [8]:
# Check the different values of the area
url_list_origin = "https://www.themealdb.com/api/json/v1/1/list.php?c=list"
ra = requests.get(url_list_origin)
df = pd.DataFrame(ra.json()["meals"])
df

      strCategory
0            Beef
1       Breakfast
2         Chicken
3         Dessert
4            Goat
5            Lamb
6   Miscellaneous
7           Pasta
8            Pork
9         Seafood
10           Side
11        Starter
12          Vegan
13     Vegetarian

In [10]:
# The string needs to be exact, otherwise, find nothing
meal_category("veggi")

Empty DataFrame
Columns: []
Index: []

In [ ]:
# Requires to create a function to generate a list